optim run build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,13 +18,13 @@ jobs:
         job: 
           # GitHub Actions Runner Images: https://github.com/actions/runner-images
           # (see also: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners)
-          - { target: x86_64-unknown-linux-musl, exe: x64-linux, os: ubuntu-latest }
-          - { target: aarch64-unknown-linux-gnu, exe: aarch64-linux, os: ubuntu-latest }
-          - { target: x86_64-pc-windows-msvc, exe: x64.exe, os: windows-latest }
-          - { target: aarch64-pc-windows-msvc, exe: aarch64.exe, os: windows-latest }
-          - { target: x86_64-apple-darwin, exe: x64-macos, os: macos-latest }
-          - { target: aarch64-apple-darwin, exe: aarch64-macos, os: macos-latest } 
-          - { target: wasm32-wasi, exe: wasi.wasm, os: ubuntu-latest }
+          - { target: x86_64-unknown-linux-musl, exe: x64-linux, os: ubuntu-latest, build_type: cargo }
+          - { target: aarch64-unknown-linux-gnu, exe: aarch64-linux, os: ubuntu-latest, build_type: cross }
+          - { target: x86_64-pc-windows-msvc, exe: x64.exe, os: windows-latest, build_type: cargo }
+          - { target: aarch64-pc-windows-msvc, exe: aarch64.exe, os: windows-latest, build_type: cargo }
+          - { target: x86_64-apple-darwin, exe: x64-macos, os: macos-latest, build_type: cargo }
+          - { target: aarch64-apple-darwin, exe: aarch64-macos, os: macos-latest, build_type: cargo } 
+          # - { target: wasm32-wasi, exe: wasi.wasm, os: ubuntu-latest, build_type: cargo }
     runs-on: ${{ matrix.job.os }}
     steps:
       - name: Checkout Repository
@@ -40,17 +40,20 @@ jobs:
 
       - name: Run Build 
         run: |
-          if [[ "${{ matrix.job.target }}" == *"x86"* || "${{ matrix.job.target }}" == *"apple"* || "${{ matrix.job.target }}" == *"windows"* ]]; then
+          if [[ "${{ matrix.job.build_type }}" == "cargo" ]]; then
             ## CARGO BUILD
             # rustup self update
             rustup target add --toolchain stable ${{ matrix.job.target }}
             rustup toolchain install --force-non-host stable
             cargo build --release --locked --target=${{ matrix.job.target }}
-          else
+          elif [[ "${{ matrix.job.build_type }}" == "cross" ]]; then
             ## CROSS BUILD
             ## (for problematic targets or fallbacks, mainly for arm/arch)
             cargo install cross # --git https://github.com/cross-rs/cross
             cross build --release --locked --target=${{ matrix.job.target }}
+          else 
+            echo "ERROR: build_type \"${{ matrix.job.build_type }}\" failed or not defined."
+            exit 1
           fi
         shell: bash
           
