Github workflow - added dynamic matrix targets

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,8 +18,15 @@ jobs:
     strategy:
       matrix:
         # os: [ubuntu-latest]
-        os: [ubuntu-latest, windows-latest, macos-latest]
-    runs-on: ${{ matrix.os }}
+        job: 
+          - { target: x86_64-unknown-linux-musl, exe: amd64-linux, os: ubuntu-latest }
+          - { target: aarch64-unknown-linux-musl, exe: aarch64-linux, os: ubuntu-latest }
+          - { target: armv7-unknown-linux-musleabi, exe: armv7-linux, os: ubuntu-latest }
+          - { target: x86_64-apple-darwin, exe: macos, os: macos-latest }
+          - { target: x86_64-pc-windows-msvc, exe: windows.exe, os: windows-2019 }
+          # - { target: wasm32-wasi, exe: wasi.wasm, os: ubuntu-latest }
+        # os: [ubuntu-latest, windows-latest, macos-latest]
+    runs-on: ${{ matrix.job.os }}
     steps:
       # - name: Checkout Repository
       #   uses: actions/checkout@v3
@@ -30,7 +37,11 @@ jobs:
       - name: Set Up Rust
         uses: actions-rs/toolchain@v1
         with:
+          profile: minimal
           toolchain: stable
+          target: ${{ matrix.job.target }}
+          override: true
+          components: rust-src # necessary for wasi, because there isn't a cross image for it
 
       # - name: Install Toolchains
       #   run: |
@@ -49,23 +60,28 @@ jobs:
       - name: Install Crossbuild Tool
         run: cargo install cross
 
-      - name: Cross Compile for Linux
-        if: startsWith(matrix.os, 'ubuntu')
+      - name: Cross Compilation
         run: |
-          cross build --release --target x86_64-unknown-linux-gnu
-          cross build --release --target aarch64-unknown-linux-gnu # TODO: NOT WORKING
+          cross build --release --locked --target=${{ matrix.job.target }}
 
-      - name: Cross Compile for macOS
-        if: startsWith(matrix.os, 'macos')
-        run: | 
-          cross build --release --target x86_64-apple-darwin
-          cross build --release --target aarch64-apple-darwin # TODO: NOT WORKING
+      # - name: Cross Compile for Linux
+      #   if: startsWith(matrix.os, 'ubuntu')
+      #   run: |
+      #     cross build --release --target x86_64-unknown-linux-gnu
+      #     cross build --release --target aarch64-unknown-linux-gnu # TODO: NOT WORKING
 
-      - name: Cross Compile for Windows
-        if: startsWith(matrix.os, 'windows')
-        run: |
-          cross build --release --target x86_64-pc-windows-gnu
-          cross build --release --target aarch64-pc-windows-msvc # TODO: MAYBE WORKING?
+      # - name: Cross Compile for macOS
+      #   if: startsWith(matrix.os, 'macos')
+      #   run: | 
+      #     cross build --release --target x86_64-apple-darwin
+      #     cross build --release --target aarch64-apple-darwin # TODO: NOT WORKING
+
+      # - name: Cross Compile for Windows
+      #   if: startsWith(matrix.os, 'windows')
+      #   run: |
+      #     cross build --release --target x86_64-pc-windows-gnu
+      #     cross build --release --target aarch64-pc-windows-msvc # TODO: MAYBE WORKING?
+
         # You may also want to generate a standalone executable:
         # run: cargo build --release --target x86_64-pc-windows-gnu --features standalone
 
@@ -76,28 +92,31 @@ jobs:
 
       - name: Archive Builds
         run: |
-          APP_NAME="rust-string-replacer"
           RUNNER_OS_LC="$(echo "$RUNNER_OS" | perl -ne 'print lc')"
           RUNNER_ARCH_LC="$(echo "$RUNNER_ARCH" | perl -ne 'print lc')"
-
+          APP_NAME="rust-string-replacer"
+          APP_NAME_SUFFIX="$(if [[ "$RUNNER_OS_LC" == "windows" ]]; then echo '.exe'; fi)"
+          
           mkdir artifacts
 
-          if [[ "$RUNNER_OS_LC" == "linux" ]]; then 
-            cp "target/x86_64-unknown-linux-gnu/release/$APP_NAME" "artifacts/$APP_NAME-$RUNNER_OS_LC-x64"
-            # cp "target/aarch64-unknown-linux-gnu/release/$APP_NAME" "artifacts/$APP_NAME-$RUNNER_OS_LC-arm64"
-            echo "ubuntu artifacts copied successfully."
-          elif [[ "$RUNNER_OS_LC" == "macos" ]]; then 
-            cp "target/x86_64-apple-darwin/release/$APP_NAME" "artifacts/$APP_NAME-$RUNNER_OS_LC-x64"
-            # cp "target/aarch64-apple-darwin/release/$APP_NAME" "artifacts/$APP_NAME-$RUNNER_OS_LC-arm64"
-            echo "osx artifacts copied successfully."
-          elif [[ "$RUNNER_OS_LC" == "windows" ]]; then 
-            cp "target/x86_64-pc-windows-gnu/release/$APP_NAME.exe" "artifacts/$APP_NAME-$RUNNER_OS_LC-x64.exe"
-            # cp "target/aarch64-pc-windows-msvc/release/$APP_NAME.exe" "artifacts/$APP_NAME-$RUNNER_OS_LC-arm64.exe"
-            echo "windows artifacts copied successfully."
-          else 
-            echo "ERROR: $RUNNER_OS_LC not supported"
-            exit 1 
-          fi
+          cp "target/${{ matrix.job.target }}/release/${APP_NAME}${APP_NAME_SUFFIX}" "artifacts/$APP_NAME-${{ matrix.job.exe }}"
+
+          # if [[ "$RUNNER_OS_LC" == "linux" ]]; then 
+          #   cp "target/x86_64-unknown-linux-gnu/release/$APP_NAME" "artifacts/$APP_NAME-$RUNNER_OS_LC-x64"
+          #   # cp "target/aarch64-unknown-linux-gnu/release/$APP_NAME" "artifacts/$APP_NAME-$RUNNER_OS_LC-arm64"
+          #   echo "ubuntu artifacts copied successfully."
+          # elif [[ "$RUNNER_OS_LC" == "macos" ]]; then 
+          #   cp "target/x86_64-apple-darwin/release/$APP_NAME" "artifacts/$APP_NAME-$RUNNER_OS_LC-x64"
+          #   # cp "target/aarch64-apple-darwin/release/$APP_NAME" "artifacts/$APP_NAME-$RUNNER_OS_LC-arm64"
+          #   echo "osx artifacts copied successfully."
+          # elif [[ "$RUNNER_OS_LC" == "windows" ]]; then 
+          #   cp "target/x86_64-pc-windows-gnu/release/$APP_NAME.exe" "artifacts/$APP_NAME-$RUNNER_OS_LC-x64.exe"
+          #   # cp "target/aarch64-pc-windows-msvc/release/$APP_NAME.exe" "artifacts/$APP_NAME-$RUNNER_OS_LC-arm64.exe"
+          #   echo "windows artifacts copied successfully."
+          # else 
+          #   echo "ERROR: $RUNNER_OS_LC not supported"
+          #   exit 1 
+          # fi
         shell: bash
 
       - name: Upload Builds
